[update to 0.49.0] Fix #414: proper handling of close method.
0qdk4o (1):
      reset WebsocketApp.sock

Andrey Bashlakov (2):
      Patch WebSocketApp class to make it inheritable
      fix README

Matt Fitzpatrick (1):
      Enable multithreading with ping_interval

Robert Xiao (1):
      Fix #414: proper handling of close method.

liris (16):
      start v0.49.0
      Merge pull request #442 from bashlakov/fix-class-inheritance
      add docs
      fixed #HC-459
      Merge pull request #446 from nneonneo/master
      add docs
      Merge pull request #448 from mfitzpatrick/ping_thread_needs_enable_multithread
      add docs
      Merge branch 'master' of https://github.com/websocket-client/websocket-client
      Merge pull request #450 from 0qdk4o/patch-1
      add docs
      fixed Attribute error on close app
      fixed #455 #443
      fixed #454
      fixed #438
      fixed #432

- 0.49.0

  - WebSocketApp class to make it inheritable (#442)
  - Add option to disable sending the Origin header (#459)
  - Websocket.close() meaning of "close status: XXXXX" (#414)
  - Enable multithreading protection with ping_interval (#448)
  - reset WebsocketApp.sock (#450)
  - websocket.enableTrace not working (#455)
  - AttributeError: 'module' object has no attribute 'NullHandler' (#443)
  - WebSocketBadStatusException "not enough arguments for format string" (#454)
  - handshake should deal with None in headers (#432)